import crypto from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { spawn } from 'node:child_process';
import { inflateRawSync } from 'node:zlib';

const repoRoot = path.resolve(import.meta.dirname, '..');
const artifactRoot = path.join(repoRoot, 'artifacts');
const evidenceRoot = path.join(repoRoot, 'verification', 'evidence');
const psql = process.env.PSQL_PATH || 'psql.exe';
const attachments = ['输入数据包.zip', 'reference.zip', '关键标准答案.xlsx', '任务规格转化.xlsx'];
const expectedReference = ['output/repair_settlement_access.sql','output/reports/database_contract.csv','output/reports/reversal_review.csv','output/reports/settlement_export.csv','output/reports/tenant_access_probe.csv'].sort();
const reportKeys = {
  'output/reports/database_contract.csv': ['object_name', 'evidence_key'],
  'output/reports/reversal_review.csv': ['voucher_id'],
  'output/reports/settlement_export.csv': ['tenant_id', 'merchant_id'],
  'output/reports/tenant_access_probe.csv': ['probe_id'],
};
const assert = (value, message) => { if (!value) throw new Error(message); };
const sha256 = (bytes) => crypto.createHash('sha256').update(bytes).digest('hex');
const sha256File = (file) => sha256(fs.readFileSync(file));

function zipEntries(file) {
  const data = fs.readFileSync(file); let eocd = -1;
  for (let index = data.length - 22; index >= Math.max(0, data.length - 65_557); index -= 1) if (data.readUInt32LE(index) === 0x06054b50) { eocd = index; break; }
  assert(eocd >= 0, `找不到ZIP目录：${file}`);
  const count = data.readUInt16LE(eocd + 10); let offset = data.readUInt32LE(eocd + 16); const entries = new Map();
  for (let entryIndex = 0; entryIndex < count; entryIndex += 1) {
    assert(data.readUInt32LE(offset) === 0x02014b50, `ZIP目录损坏：${file}`);
    const method = data.readUInt16LE(offset + 10); const compressedSize = data.readUInt32LE(offset + 20); const uncompressedSize = data.readUInt32LE(offset + 24);
    const nameLength = data.readUInt16LE(offset + 28); const extraLength = data.readUInt16LE(offset + 30); const commentLength = data.readUInt16LE(offset + 32); const localOffset = data.readUInt32LE(offset + 42);
    const name = data.subarray(offset + 46, offset + 46 + nameLength).toString('utf8').replaceAll('\\', '/');
    const localNameLength = data.readUInt16LE(localOffset + 26); const localExtraLength = data.readUInt16LE(localOffset + 28); const start = localOffset + 30 + localNameLength + localExtraLength;
    if (!name.endsWith('/')) { const compressed = data.subarray(start, start + compressedSize); const body = method === 0 ? compressed : method === 8 ? inflateRawSync(compressed) : null; assert(body && body.length === uncompressedSize, `无法解压${name}`); entries.set(name, body); }
    offset += 46 + nameLength + extraLength + commentLength;
  }
  return entries;
}
async function extract(file, destination) { for (const [name, bytes] of zipEntries(file)) { const target = path.resolve(destination, ...name.split('/')); assert(target.startsWith(`${path.resolve(destination)}${path.sep}`), `非法ZIP路径：${name}`); await fsp.mkdir(path.dirname(target), { recursive: true }); await fsp.writeFile(target, bytes); } }
function workbookSheets(file) { const xml = zipEntries(file).get('xl/workbook.xml')?.toString('utf8') ?? ''; return [...xml.matchAll(/<(?:[A-Za-z]+:)?sheet[^>]+name="([^"]+)"/gu)].map((match) => match[1]); }
async function run(command, args, cwd, env = {}) {
  const started = Date.now(); return await new Promise((resolve) => {
    let child; try { child = spawn(command, args, { cwd, env: { ...process.env, ...env }, windowsHide: true }); } catch (error) { resolve({ code: 1, stdout: '', stderr: error.stack ?? error.message, elapsed_ms: Date.now() - started }); return; }
    let stdout = ''; let stderr = ''; let settled = false; child.stdout.on('data', (chunk) => { stdout += chunk; }); child.stderr.on('data', (chunk) => { stderr += chunk; });
    child.on('error', (error) => { if (!settled) { settled = true; resolve({ code: 1, stdout, stderr: `${stderr}${error.stack ?? error.message}`, elapsed_ms: Date.now() - started }); } }); child.on('exit', (code) => { if (!settled) { settled = true; resolve({ code: code ?? 1, stdout, stderr, elapsed_ms: Date.now() - started }); } });
  });
}
async function psqlRun(database, args) { return await run(psql, ['-X', '-d', database, ...args], repoRoot, { PGDATABASE: database }); }
async function scalar(database, sql) { const result = await psqlRun(database, ['-At', '-v', 'ON_ERROR_STOP=1', '-c', sql]); assert(result.code === 0, `PostgreSQL查询失败\n${result.stderr || result.stdout}`); return result.stdout.trim(); }
async function createDatabase(name) { await psqlRun('postgres', ['-v', 'ON_ERROR_STOP=1', '-c', `DROP DATABASE IF EXISTS ${name} WITH (FORCE)`]); const result = await psqlRun('postgres', ['-v', 'ON_ERROR_STOP=1', '-c', `CREATE DATABASE ${name}`]); assert(result.code === 0, `创建数据库失败：${name}\n${result.stderr}`); }
async function dropDatabase(name) { await psqlRun('postgres', ['-v', 'ON_ERROR_STOP=1', '-c', `DROP DATABASE IF EXISTS ${name} WITH (FORCE)`]); }
async function runTask(inputRoot, database) { return await run('pwsh', ['-NoLogo', '-NoProfile', '-File', path.join(inputRoot, 'tools', 'run-task.ps1'), '-PsqlPath', psql], inputRoot, { PGDATABASE: database }); }
function parseCsv(text) {
  const rows = []; let row = []; let cell = ''; let quoted = false;
  for (let index = 0; index < text.length; index += 1) { const char = text[index]; if (quoted) { if (char === '"' && text[index + 1] === '"') { cell += '"'; index += 1; } else if (char === '"') quoted = false; else cell += char; } else if (char === '"') quoted = true; else if (char === ',') { row.push(cell); cell = ''; } else if (char === '\n') { row.push(cell.replace(/\r$/u, '')); rows.push(row); row = []; cell = ''; } else cell += char; }
  if (cell || row.length) { row.push(cell.replace(/\r$/u, '')); rows.push(row); } const headers = rows.shift() ?? []; return rows.filter((values) => values.some((value) => value !== '')).map((values) => Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ''])));
}
function normalizedRows(file, text) { const rows = parseCsv(text); const keys = reportKeys[file]; return rows.toSorted((left, right) => keys.map((key) => String(left[key]).localeCompare(String(right[key]), 'en')).find((value) => value !== 0) ?? 0); }
function files(root) { const result = []; function walk(current, prefix = '') { if (!fs.existsSync(current)) return; for (const entry of fs.readdirSync(current, { withFileTypes: true }).toSorted((a, b) => a.name.localeCompare(b.name, 'en'))) { const relative = prefix ? `${prefix}/${entry.name}` : entry.name; if (entry.isDirectory()) walk(path.join(current, entry.name), relative); else result.push(relative); } } walk(root); return result.sort(); }
function treeDigest(root, ignored = new Set()) { const lines = []; function walk(current, prefix = '') { for (const entry of fs.readdirSync(current, { withFileTypes: true }).toSorted((a, b) => a.name.localeCompare(b.name, 'en'))) { const relative = prefix ? `${prefix}/${entry.name}` : entry.name; if (ignored.has(relative.split('/')[0])) continue; const full = path.join(current, entry.name); if (entry.isDirectory()) walk(full, relative); else lines.push(`${relative}\0${sha256File(full)}`); } } walk(root); return sha256(Buffer.from(lines.join('\n'))); }
function classifyExecutable(name, bytes) { const lower = name.toLowerCase(); if (bytes.length >= 4 && bytes[0] === 0x7f && bytes.subarray(1, 4).toString('ascii') === 'ELF') return 'linux_elf'; if (/\.(?:sh|bash|so)(?:\.|$)/u.test(lower)) return 'posix_member'; if (/^#!.*(?:ba|z|k)?sh/mu.test(bytes.subarray(0, 160).toString('utf8'))) return 'posix_shebang'; return null; }
async function prepare(label, database, mutate) { const root = path.join(os.tmpdir(), label); await fsp.rm(root, { recursive: true, force: true }); await fsp.mkdir(root, { recursive: true }); await extract(path.join(artifactRoot, '输入数据包.zip'), root); const inputRoot = path.join(root, 'input_data'); const reference = zipEntries(path.join(artifactRoot, 'reference.zip')); const outputRoot = path.join(inputRoot, 'output'); await fsp.mkdir(outputRoot, { recursive: true }); await fsp.writeFile(path.join(outputRoot, 'repair_settlement_access.sql'), reference.get('output/repair_settlement_access.sql')); if (mutate) await mutate(inputRoot); await createDatabase(database); return { inputRoot, outputRoot, reference, database }; }
async function compareReference(room) {
  const actualPaths = files(room.outputRoot).map((name) => `output/${name}`); assert(JSON.stringify(actualPaths) === JSON.stringify(expectedReference), `输出成员与标准交付不一致：${actualPaths.join(',')}`);
  const actualSql = fs.readFileSync(path.join(room.outputRoot, 'repair_settlement_access.sql'), 'utf8').replaceAll('\r\n', '\n'); const expectedSql = room.reference.get('output/repair_settlement_access.sql').toString('utf8').replaceAll('\r\n', '\n'); assert(actualSql === expectedSql, '完成版SQL与标准交付不一致'); const semantic = crypto.createHash('sha256'); semantic.update(actualSql);
  for (const file of expectedReference.filter((name) => name.endsWith('.csv'))) { const actualRows = normalizedRows(file, fs.readFileSync(path.join(room.inputRoot, ...file.split('/')), 'utf8')); const expectedRows = normalizedRows(file, room.reference.get(file).toString('utf8')); assert(JSON.stringify(actualRows) === JSON.stringify(expectedRows), `${file}业务字段不一致\n实际：${JSON.stringify(actualRows)}\n预期：${JSON.stringify(expectedRows)}`); semantic.update(JSON.stringify(actualRows)); }
  assert(await scalar(room.database, "SELECT concat((SELECT count(*) FROM raw.raw_tenant_account),',',(SELECT count(*) FROM raw.raw_merchant_profile),',',(SELECT count(*) FROM raw.raw_settlement_ledger))") === '3,7,19', '原始来源表行数错误');
  assert(await scalar(room.database, 'SELECT count(*) FROM settlement.policy') === '15', '策略副本行数错误'); assert(await scalar(room.database, "SELECT count(*) FROM settlement.settlement_ledger WHERE voucher_id IN('V-A-009','V-A-010','V-B-006','V-B-007')") === '0', '被拒绝冲销进入受控账本'); assert(await scalar(room.database, "SELECT count(*) FROM settlement.settlement_ledger WHERE voucher_id IN('V-A-008','V-B-005')") === '2', '有效冲销未进入受控账本'); assert(await scalar(room.database, "SELECT count(*) FROM settlement.settlement_ledger WHERE voucher_id='PROBE-OWN'") === '0', '临时写入未回滚'); return semantic.digest('hex');
}

await fsp.rm(evidenceRoot, { recursive: true, force: true }); await fsp.mkdir(evidenceRoot, { recursive: true }); assert(process.platform === 'win32' && process.env.GITHUB_ACTIONS === 'true', '只接受GitHub托管Windows运行');
const clientVersion = await run(psql, ['--version'], repoRoot); assert(clientVersion.code === 0 && /PostgreSQL\) 17\./u.test(clientVersion.stdout), `需要psql17，当前为${clientVersion.stdout || clientVersion.stderr}`); const serverVersion = await scalar('postgres', 'SHOW server_version_num'); assert(serverVersion.startsWith('17'), `需要PostgreSQL17服务，当前为${serverVersion}`);
const attachmentSha256 = Object.fromEntries(attachments.map((name) => [name, sha256File(path.join(artifactRoot, name))])); const inputMembers = zipEntries(path.join(artifactRoot, '输入数据包.zip')); const executableScan = [...inputMembers].map(([name, bytes]) => ({ name, classification: classifyExecutable(name, bytes) })).filter((item) => item.classification);
assert(executableScan.length === 0, `输入包含平台专用成员：${JSON.stringify(executableScan)}`); assert(JSON.stringify([...zipEntries(path.join(artifactRoot, 'reference.zip')).keys()].sort()) === JSON.stringify(expectedReference), '标准交付成员错误'); assert(JSON.stringify(workbookSheets(path.join(artifactRoot, '关键标准答案.xlsx'))) === JSON.stringify(['交付物答案清单', '固定字段答案', '固定集合答案', '固定数值答案', '允许变体答案']), '关键标准答案Sheet错误'); assert(JSON.stringify(workbookSheets(path.join(artifactRoot, '任务规格转化.xlsx'))) === JSON.stringify(['任务规格转化']), '任务规格Sheet错误');
const solution = zipEntries(path.join(artifactRoot, 'reference.zip')).get('output/repair_settlement_access.sql').toString('utf8'); assert(!/\b(?:TNA|TNB|M100|M101|M200|M201|V-A-\d+|V-B-\d+)\b/u.test(solution), '完成版SQL含样例业务主键硬编码');
const cleanRuns = [];
for (const [label, database] of [['Q10413 第一处 中文 空目录', 'q10413_clean_a'], ['Q10413 第二处 中文 空格目录', 'q10413_clean_b']]) { const room = await prepare(label, database); try { const before = treeDigest(room.inputRoot, new Set(['output'])); const first = await runTask(room.inputRoot, database); assert(first.code === 0, `${label}首次运行失败\n${first.stdout}\n${first.stderr}`); const firstSemantic = await compareReference(room); const second = await runTask(room.inputRoot, database); assert(second.code === 0, `${label}第二次运行失败\n${second.stdout}\n${second.stderr}`); const after = treeDigest(room.inputRoot, new Set(['output'])); assert(before === after, `${label}修改了输入`); const semantic = await compareReference(room); assert(firstSemantic === semantic, `${label}两次结构化结果不一致`); cleanRuns.push({ directory_label: label, database, process_runs: 2, exit_codes: [first.code, second.code], input_digest_before: before, input_digest_after: after, semantic_digest: semantic, elapsed_ms: [first.elapsed_ms, second.elapsed_ms], reference_match: true }); } finally { await dropDatabase(database); } }
assert(cleanRuns[0].semantic_digest === cleanRuns[1].semantic_digest, '两个目录的结构化结果不一致');
const crlf = await prepare('Q10413 CRLF 报表布局', 'q10413_crlf', async (inputRoot) => { const file = path.join(inputRoot, 'rules', 'report_layout.csv'); const value = await fsp.readFile(file, 'utf8'); await fsp.writeFile(file, value.replace(/\r?\n/gu, '\r\n')); }); let result; let crlfDigest;
try { result = await runTask(crlf.inputRoot, crlf.database); assert(result.code === 0, `CRLF报表布局运行失败\n${result.stdout}\n${result.stderr}`); crlfDigest = await compareReference(crlf); assert(crlfDigest === cleanRuns[0].semantic_digest, 'CRLF报表布局改变业务结果'); } finally { await dropDatabase(crlf.database); }
const mutation = await prepare('Q10413 结算截止时间变化', 'q10413_mutation', async (inputRoot) => { const file = path.join(inputRoot, 'rules', 'settlement_policy.csv'); const value = await fsp.readFile(file, 'utf8'); await fsp.writeFile(file, value.replace('2026-07-16T00:00:00Z', '2026-07-09T00:00:00Z')); }); let changedMerchant;
try { result = await runTask(mutation.inputRoot, mutation.database); assert(result.code === 0, `结算截止时间变化运行失败\n${result.stdout}\n${result.stderr}`); const rows = parseCsv(await fsp.readFile(path.join(mutation.outputRoot, 'reports', 'settlement_export.csv'), 'utf8')); changedMerchant = rows.find((row) => row.tenant_id === 'TNA' && row.merchant_id === 'M100'); assert(JSON.stringify(changedMerchant) === JSON.stringify({ tenant_id: 'TNA', merchant_id: 'M100', merchant_name: 'Active Threads', currency: 'USD', posted_entry_count: '3', gross_cents: '20300', fee_cents: '744', net_cents: '19556', reversed_original_count: '0', statement_status: 'ready' }), `结算截止时间没有联动商户结果：${JSON.stringify(changedMerchant)}`); } finally { await dropDatabase(mutation.database); }
const negative = await prepare('Q10413 缺失结算策略', 'q10413_invalid', async (inputRoot) => { await fsp.rm(path.join(inputRoot, 'rules', 'settlement_policy.csv')); });
try { result = await runTask(negative.inputRoot, negative.database); const reportsAbsent = !fs.existsSync(path.join(negative.outputRoot, 'reports')); const solutionPreserved = fs.existsSync(path.join(negative.outputRoot, 'repair_settlement_access.sql')); assert(result.code !== 0 && reportsAbsent && solutionPreserved, '结算策略缺失时没有失败关闭'); } finally { await dropDatabase(negative.database); }
const evidence = { schema_version: 1, task_asset_id: 'postgres_settlement_access_reversal_review', result: 'PASS', generated_at_utc: new Date().toISOString(), git_commit_sha: process.env.GITHUB_SHA, workflow_run_id: process.env.GITHUB_RUN_ID, runner: { os: process.env.RUNNER_OS, arch: process.env.RUNNER_ARCH, image_os: process.env.ImageOS, image_version: process.env.ImageVersion, node: process.version, actual_windows_run: true, powershell_hosted_workflow: true }, software: { psql: clientVersion.stdout.trim(), server_version_num: serverVersion, powershell: 'pwsh-hosted' }, attachment_sha256: attachmentSha256, archive_checks: { input_members: [...inputMembers.keys()].sort(), reference_members: expectedReference, prohibited_platform_members: executableScan }, workbook_checks: { answer_sheet_names: workbookSheets(path.join(artifactRoot, '关键标准答案.xlsx')), specification_sheet_names: workbookSheets(path.join(artifactRoot, '任务规格转化.xlsx')) }, clean_runs: cleanRuns, crlf_case: { changed_input: 'rules/report_layout.csv行尾改为CRLF', exit_code: 0, semantic_digest: crlfDigest, reference_match: true }, positive_mutation: { changed_rule: 'report_end_utc从2026-07-16改为2026-07-09', exit_code: 0, changed_merchant: changedMerchant }, invalid_input: { removed_input: 'rules/settlement_policy.csv', exit_code: result.code, reports_absent: !fs.existsSync(path.join(negative.outputRoot, 'reports')), solution_preserved: fs.existsSync(path.join(negative.outputRoot, 'repair_settlement_access.sql')) }, network: { installation_network_access: '仅PostgreSQL安装阶段', formal_run_network_access: 'none' } };
await fsp.writeFile(path.join(evidenceRoot, 'windows-verification.json'), `${JSON.stringify(evidence, null, 2)}\n`); const audit = { schema_version: 1, task_asset_id: evidence.task_asset_id, result: 'PASS', platform: process.platform, architecture: process.arch, node_version: process.version, psql_version: clientVersion.stdout.trim(), server_version_num: serverVersion, attachment_sha256: attachmentSha256, input_members: evidence.archive_checks.input_members, reference_members: evidence.archive_checks.reference_members, forbidden_platform_members: executableScan, clean_directory_count: cleanRuns.length, process_runs_per_directory: 2 };
await fsp.writeFile(path.join(evidenceRoot, 'windows-audit.json'), `${JSON.stringify(audit, null, 2)}\n`); console.log(JSON.stringify(evidence, null, 2));
